name: Build the app
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  # Build
  build:
    name: Building the app...
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Build
        run: bun run build
